# Site settings
title: "Winston Hearn III puts his stuff here"
subtitle: "While I'm alive, I'll make tiny changes to earth."
author: Winston Hearn
email: hello@wnstn.com
description: >
  Worldwide homepage and base of operations for Winston Hearn,
  a person who uses the internet and is learning about things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://winstonhearn.com" # the base hostname & protocol for your site
twitter_username: suchwinston
github_username:  wnstn

# Build settings
markdown: kramdown
paginate: 16
exclude:
  - package.json
  - node_modules
  - gulpfile.js
