# Site settings
title: Winston Hearn opines here
subtitle: sometimes they listen
author: Winston Hearn
email: hello@wnstn.com
description: > # this means to ignore newlines until "baseurl:"
  Worldwide homepage and base of operations for Winston Hearn,
  a person who uses the internet and has opinions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://winstonhearn.com" # the base hostname & protocol for your site
twitter_username: suchwinston
github_username:  wnstn

# Build settings
markdown: kramdown
